package com.example.project.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.ColumnDefault;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

@Getter
@Setter
@Entity
@Table(name = "vatinvoice")
public class Vatinvoice {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "vatInvoiceID", nullable = false)
    private Integer id;

    @NotNull
    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "invoiceID", nullable = false)
    private Invoice invoiceID;

    @Size(max = 50)
    @NotNull
    @Column(name = "vatInvoiceNumber", nullable = false, length = 50)
    private String vatInvoiceNumber;

    @Size(max = 10)
    @NotNull
    @Column(name = "vatInvoiceSeries", nullable = false, length = 10)
    private String vatInvoiceSeries;

    @NotNull
    @Column(name = "issuedDate", nullable = false)
    private LocalDate issuedDate;

    @Size(max = 255)
    @Column(name = "buyerName")
    private String buyerName;

    @Size(max = 20)
    @Column(name = "buyerTaxCode", length = 20)
    private String buyerTaxCode;

    @Lob
    @Column(name = "buyerAddress")
    private String buyerAddress;

    @Size(max = 50)
    @Column(name = "buyerBankAccount", length = 50)
    private String buyerBankAccount;

    @Size(max = 20)
    @NotNull
    @Column(name = "sellerTaxCode", nullable = false, length = 20)
    private String sellerTaxCode;

    @NotNull
    @Column(name = "taxableAmount", nullable = false, precision = 15, scale = 2)
    private BigDecimal taxableAmount;

    @NotNull
    @Column(name = "vatAmount", nullable = false, precision = 15, scale = 2)
    private BigDecimal vatAmount;

    @NotNull
    @Column(name = "totalAmount", nullable = false, precision = 15, scale = 2)
    private BigDecimal totalAmount;

    @Column(name = "signedAt")
    private Instant signedAt;

    @Column(name = "cancelledAt")
    private Instant cancelledAt;

    @Lob
    @Column(name = "cancelReason")
    private String cancelReason;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "originalVATInvoiceID")
    private Vatinvoice originalVATInvoiceID;

    @ColumnDefault("'NONE'")
    @Lob
    @Column(name = "adjustmentType")
    private String adjustmentType;

    @Lob
    @Column(name = "adjustmentReason")
    private String adjustmentReason;

    @ColumnDefault("0")
    @Column(name = "autoGenerated")
    private Boolean autoGenerated;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "returnID")
    private Return returnID;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusID")
    private Status statusID;

    @Lob
    @Column(name = "note")
    private String note;


}