package com.example.project.dto.response;

import com.example.project.entity.Vatinvoice;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class VatinvoiceResponse {
    private Integer id;
    private Integer invoiceId;
    private String vatInvoiceNumber;
    private String vatInvoiceSeries;
    private LocalDate issuedDate;
    private String buyerName;
    private String buyerTaxCode;
    private String buyerAddress;
    private String buyerBankAccount;
    private String sellerTaxCode;
    private BigDecimal taxableAmount;
    private BigDecimal vatAmount;
    private BigDecimal totalAmount;
    private Instant signedAt;
    private Instant cancelledAt;
    private String cancelReason;
    private Integer originalVATInvoiceId;
    private String adjustmentType;
    private String adjustmentReason;
    private Boolean autoGenerated;
    private Integer returnId;
    private Integer statusId;
    private String note;

    public static VatinvoiceResponse from(Vatinvoice vatinvoice) {
        return new VatinvoiceResponse(
                vatinvoice.getId(),
                vatinvoice.getInvoiceID() != null ? vatinvoice.getInvoiceID().getId() : null,
                vatinvoice.getVatInvoiceNumber(),
                vatinvoice.getVatInvoiceSeries(),
                vatinvoice.getIssuedDate(),
                vatinvoice.getBuyerName(),
                vatinvoice.getBuyerTaxCode(),
                vatinvoice.getBuyerAddress(),
                vatinvoice.getBuyerBankAccount(),
                vatinvoice.getSellerTaxCode(),
                vatinvoice.getTaxableAmount(),
                vatinvoice.getVatAmount(),
                vatinvoice.getTotalAmount(),
                vatinvoice.getSignedAt(),
                vatinvoice.getCancelledAt(),
                vatinvoice.getCancelReason(),
                vatinvoice.getOriginalVATInvoiceID() != null ? vatinvoice.getOriginalVATInvoiceID().getId() : null,
                vatinvoice.getAdjustmentType(),
                vatinvoice.getAdjustmentReason(),
                vatinvoice.getAutoGenerated(),
                vatinvoice.getReturnID() != null ? vatinvoice.getReturnID().getId() : null,
                vatinvoice.getStatusID() != null ? vatinvoice.getStatusID().getId() : null,
                vatinvoice.getNote()
        );
    }
}